services:
  db:
    image: mysql:latest
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  api:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: dev
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./api:/api
      - ./api/vendor:/api/vendor
    depends_on:
      db:
        condition: service_healthy
  
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./spa:/spa
      - /spa/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      target: dev
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/public:/api/public
    ports:
      - '127.0.0.3:80:80'
    depends_on:
      - spa
      - api

volumes:
  mysql_data: