services:
  db:
    image: mysql:latest
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  api:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: prod
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      db:
        condition: service_healthy
  
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - api

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      target: prod
    ports:
      - '127.0.0.3:80:80'
    depends_on:
      - spa
      - api

volumes:
  mysql_data: